M	TODO_DESKTOP.md
M	apps/desktop/src-tauri/Cargo.toml
A	apps/desktop/src-tauri/build.rs
A	apps/desktop/src-tauri/gen/schemas/acl-manifests.json
A	apps/desktop/src-tauri/gen/schemas/capabilities.json
A	apps/desktop/src-tauri/gen/schemas/desktop-schema.json
A	apps/desktop/src-tauri/gen/schemas/windows-schema.json
A	apps/desktop/src-tauri/icon.png
A	apps/desktop/src-tauri/icons/128x128.png
A	apps/desktop/src-tauri/icons/128x128@2x.png
A	apps/desktop/src-tauri/icons/32x32.png
A	apps/desktop/src-tauri/icons/64x64.png
A	apps/desktop/src-tauri/icons/Square107x107Logo.png
A	apps/desktop/src-tauri/icons/Square142x142Logo.png
A	apps/desktop/src-tauri/icons/Square150x150Logo.png
A	apps/desktop/src-tauri/icons/Square284x284Logo.png
A	apps/desktop/src-tauri/icons/Square30x30Logo.png
A	apps/desktop/src-tauri/icons/Square310x310Logo.png
A	apps/desktop/src-tauri/icons/Square44x44Logo.png
A	apps/desktop/src-tauri/icons/Square71x71Logo.png
A	apps/desktop/src-tauri/icons/Square89x89Logo.png
A	apps/desktop/src-tauri/icons/StoreLogo.png
A	apps/desktop/src-tauri/icons/android/mipmap-hdpi/ic_launcher.png
A	apps/desktop/src-tauri/icons/android/mipmap-hdpi/ic_launcher_foreground.png
A	apps/desktop/src-tauri/icons/android/mipmap-hdpi/ic_launcher_round.png
A	apps/desktop/src-tauri/icons/android/mipmap-mdpi/ic_launcher.png
A	apps/desktop/src-tauri/icons/android/mipmap-mdpi/ic_launcher_foreground.png
A	apps/desktop/src-tauri/icons/android/mipmap-mdpi/ic_launcher_round.png
A	apps/desktop/src-tauri/icons/android/mipmap-xhdpi/ic_launcher.png
A	apps/desktop/src-tauri/icons/android/mipmap-xhdpi/ic_launcher_foreground.png
A	apps/desktop/src-tauri/icons/android/mipmap-xhdpi/ic_launcher_round.png
A	apps/desktop/src-tauri/icons/android/mipmap-xxhdpi/ic_launcher.png
A	apps/desktop/src-tauri/icons/android/mipmap-xxhdpi/ic_launcher_foreground.png
A	apps/desktop/src-tauri/icons/android/mipmap-xxhdpi/ic_launcher_round.png
A	apps/desktop/src-tauri/icons/android/mipmap-xxxhdpi/ic_launcher.png
A	apps/desktop/src-tauri/icons/android/mipmap-xxxhdpi/ic_launcher_foreground.png
A	apps/desktop/src-tauri/icons/android/mipmap-xxxhdpi/ic_launcher_round.png
A	apps/desktop/src-tauri/icons/icon.icns
A	apps/desktop/src-tauri/icons/icon.ico
A	apps/desktop/src-tauri/icons/icon.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-20x20@1x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-20x20@2x-1.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-20x20@2x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-20x20@3x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-29x29@1x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-29x29@2x-1.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-29x29@2x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-29x29@3x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-40x40@1x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-40x40@2x-1.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-40x40@2x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-40x40@3x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-512@2x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-60x60@2x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-60x60@3x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-76x76@1x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-76x76@2x.png
A	apps/desktop/src-tauri/icons/ios/AppIcon-83.5x83.5@2x.png
M	apps/desktop/src-tauri/src/main.rs
M	apps/desktop/ui/package.json
M	apps/desktop/ui/src/modules/App.tsx
